# Generated by Django 2.2.3 on 2019-07-09 12:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
